# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20170821_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrecord',
            name='criteria1',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AddField(
            model_name='clubrecord',
            name='criteria2',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AddField(
            model_name='clubrecord',
            name='criteria3',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
