# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20170823_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubrecord',
            old_name='criteria3',
            new_name='criteria0',
        ),
    ]
