# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20170823_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubrecord',
            name='criteria0',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='clubrecord',
            name='criteria1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='clubrecord',
            name='criteria2',
            field=models.CharField(default='', max_length=250),
        ),
    ]
